### PR TITLE
Draftsim design

### PR DESCRIPTION
**Pull request by xAz**
http://goo.gl/tj2YXT

### CODE REVIEW

**Comment by xAz** [comment]
Are we merging this before BfZ comes out?

**Comment by scottchiefbaker** [comment]
I just tested this and it looks gorgeous. If my vote counts for anything, I think we should merge this before the launch.

The **only** gripe I could fine was that the cards are all right next to each other. Can we add a `padding: 3px` to spread the cards out a little?

**Comment by xAz** [comment]
Thanks Scott. It's supposed to be a starting point, a real barebones version.

**Comment by danieljbrooks** [comment]
Great work!

I believe that I just merged the changes. Taking a closer look now.

Scott - I agree that 3px padding has a nice look to it. Let's try implementing that again. I recall trying and having CSS ignore that line :).

**Comment by danieljbrooks** [comment]
Hey, great stuff, very promising! The new look is professional and stylish!

This is currently being hosted at the "beta" version of the draftsim site at:
http://draftsim.com/beta/about.php

A few comments:
-The fonts for the buttons and text can be larger to improve visibility
-Unselectable card images and table of card values
-Mobile: the new design is 3 cards across on an iPhone 6, down from 4. Maybe there's more border padding?
-A little bit of spacing between the cards looks nice

**Pull request merged**
