### PR TITLE
Move CSS to their own dir, fix some links, and add some CSS padding...

### PR DESCRIPTION
**Pull request by scottchiefbaker**

### CODE REVIEW

**Comment by danieljbrooks** [comment]
Thanks Scott, looks good, I will review and push to live!

**Comment by scottchiefbaker** [comment]
You need to click Merge pull request to actually pull this code in to your repo.

**Comment by danieljbrooks** [comment]
Yes, but I ended up merging it with the live site code, which was a little different than the current code. Check the danieljbrooks/draftsim-launch directory for the updated code

**Comment by danieljbrooks** [comment]
Github has had been unresponsive for me today. Is this the case for you
guys?

In any case, I've merged the commits from you guys with the live website
code and posted it to my Github. I've made some minor changes between
launch and today, so be sure to use the updated code

From now on, I will update the website with code directly from the Github
to ensure consistent versions.

**Comment by arxanas** [comment]
@danieljbrooks: Have you considered any automation regarding updating the website? For example, Github supports webhooks. If you have a script on your server, you can get Github to make a web request to it whenever there's activity on `master`. This script could just `git pull` in the repo.

**Comment by danieljbrooks** [comment]
That could be a good idea. I'd like to get a sense of what the current
upload update/upload is like. Maybe revisit in a week or two?

**Pull request closed without merging**
