### PR TITLE
The Great Cleanup

### PR DESCRIPTION
**Pull request by xAz**
Reorganised structure.
Removed unneccesary files.
Prepared stuff for design implementation.

Added:
- Bootstrap
- Chart.js (non-functional)
- jQuery

### CODE REVIEW

**Comment by danieljbrooks** [comment]
Nice! When the design goes through, let's merge this with the master repo

**Comment by xAz** [comment]
I'm not sure, do i keep working on this branch then?

**Comment by scottchiefbaker** [comment]
@xAz I just checked out your branch it looks amazing! I really like the visual upgrade, well done.

It looks like there have been some changes in `master` that don't cleanly merge in with this design branch. Step #1 would be to resolve all those conflicts so we can merge this in cleanly, and update everything.

Again, GREAT work. I really like what you did.

**Comment by danieljbrooks** [comment]
Yes, keep going on the branch!

When I get a chance, I'll merge the card image loading upgrade and get the visual upgrade to master branch.

**Comment by xAz** [comment]
Thanks! Glad to be able to give something back to the community. I'll try to update this morning.

**Comment by xAz** [comment]
Updated but don't feel comfortable merging myself. Please review carefully.

**Pull request closed without merging**
